import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SITE_BASE = "https://riaevangelist.github.io/RIAEvangelist/";
const PAGE_SIZE = 8;
const CHECK_MODE = process.argv.includes("--check");

function xmlEscape(value) {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&apos;");
}

function entry(route, changefreq, priority) {
  return `  <url>\n    <loc>${xmlEscape(`${SITE_BASE}${route}`)}</loc>\n    <changefreq>${changefreq}</changefreq>\n    <priority>${priority}</priority>\n  </url>`;
}

async function main() {
  const [music, story] = await Promise.all([
    readFile(path.join(ROOT, "data", "music.json"), "utf8").then(JSON.parse),
    readFile(path.join(ROOT, "data", "story.json"), "utf8").then(JSON.parse)
  ]);

  const routes = [
    ["", "daily", "1.0"],
    ["music/", "monthly", "0.9"],
    ["music/process/", "yearly", "0.8"],
    ["music/origins/", "yearly", "0.8"],
    ["music/releases/", "monthly", "0.9"],
    ...Array.from({ length: Math.ceil(music.releases.length / PAGE_SIZE) - 1 }, (_, index) => [
      `music/releases/page/${index + 2}/`,
      "monthly",
      "0.7"
    ]),
    ["music/collections/", "monthly", "0.8"],
    ...music.collections.map(({ slug }) => [`music/collections/${slug}/`, "monthly", "0.7"]),
    ...music.releases.map(({ slug }) => [`music/releases/${slug}/`, "monthly", "0.8"]),
    ["story/", "monthly", "0.9"],
    ...story.pages.map(({ slug }) => [`story/${slug}/`, "monthly", "0.8"])
  ];

  const uniqueRoutes = new Set(routes.map(([route]) => route));
  if (uniqueRoutes.size !== routes.length) throw new Error("Duplicate sitemap route");

  const sitemap = `<?xml version="1.0" encoding="UTF-8"?>\n<!-- Generated by scripts/generate-sitemap.mjs. Do not edit directly. -->\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${routes.map((item) => entry(...item)).join("\n")}\n</urlset>\n`;
  const destination = path.join(ROOT, "sitemap.xml");
  const current = await readFile(destination, "utf8").catch(() => null);

  if (CHECK_MODE) {
    if (current !== sitemap) throw new Error("sitemap.xml is stale; run node scripts/generate-sitemap.mjs");
    console.log(`Verified ${routes.length} sitemap routes.`);
    return;
  }

  if (current !== sitemap) await writeFile(destination, sitemap, "utf8");
  console.log(`Generated ${routes.length} sitemap routes.`);
}

await main();
